version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt -t python/
  build:
    commands:
      - cp lambda_function.py python/
      - zip -r function.zip python/

artifacts:
  files:
    - function.zip
